/**
 *
 * $Id$
 */
package Trialple.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Trialple.ArgxType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ArgxTypeValidator {
	boolean validate();

	boolean validateArgstring(EList<String> value);
	boolean validateSep(String value);
}
