/**
 *
 * $Id$
 */
package Trialple.validation;

import Trialple.ModuleList;
import Trialple.UnitDefinition;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Trialple.ExecutionControl}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExecutionControlValidator {
	boolean validate();

	boolean validateModules(EList<ModuleList> value);
	boolean validateUnitDefinition(EList<UnitDefinition> value);
	boolean validateName(String value);
	boolean validateSrcid(String value);
	boolean validateVersion(String value);
}
