/**
 *
 * $Id$
 */
package Trialple.validation;

import Trialple.OptList;
import Trialple.Phase;
import Trialple.SubModuleRef;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Trialple.IfType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IfTypeValidator {
	boolean validate();

	boolean validatePhase(EList<Phase> value);
	boolean validateOptions(EList<OptList> value);
	boolean validateSubmoduleref(EList<SubModuleRef> value);
	boolean validateTest(String value);
}
