/**
 *
 * $Id$
 */
package Trialple.validation;

import Trialple.Module;
import Trialple.Modules;
import Trialple.SubmoduleDef;
import Trialple.SubmoduleDefs;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Trialple.ModuleList}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModuleListValidator {
	boolean validate();

	boolean validateModule(EList<Module> value);
	boolean validateModules(EList<Modules> value);
	boolean validateSubmoduledefs(EList<SubmoduleDefs> value);
	boolean validateSubmoduledef(EList<SubmoduleDef> value);
}
