/**
 *
 * $Id$
 */
package Trialple.validation;

import Trialple.ModuleType;
import Trialple.OptList;
import Trialple.Phaselist;
import Trialple.Precedences;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Trialple.Module}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModuleValidator {
	boolean validate();

	boolean validateDescription(String value);

	boolean validateDescription(EList<String> value);
	boolean validateOptions(OptList value);
	boolean validatePostevent(String value);
	boolean validateRevokemodule(String value);
	boolean validatePassword(String value);
	boolean validatePrecedences(EList<Precedences> value);
	boolean validatePhaselist(Phaselist value);
	boolean validateCheckmode(String value);
	boolean validateErrignorable(String value);
	boolean validateInterruptable(String value);
	boolean validateMandatory(String value);
	boolean validateName(String value);
	boolean validateReselect(String value);
	boolean validateRevokeautonext(String value);
	boolean validateType(ModuleType value);
	boolean validateUniqueexec(String value);
}
