/**
 *
 * $Id$
 */
package Trialple.validation;

import Trialple.IfType;
import Trialple.Phase;
import Trialple.SubModule;
import Trialple.SubModuleRef;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Trialple.Phaselist}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PhaselistValidator {
	boolean validate();

	boolean validatePhase(EList<Phase> value);
	boolean validateIf(EList<IfType> value);
	boolean validateSubmodule(EList<SubModule> value);
	boolean validateSubmoduleref(EList<SubModuleRef> value);
	boolean validateSrcid(String value);
}
