/**
 *
 * $Id$
 */
package Trialple.validation;

import Trialple.Definitions;
import Trialple.Phaselist;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Trialple.SubmoduleDef}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SubmoduleDefValidator {
	boolean validate();

	boolean validateDefs(Definitions value);
	boolean validatePhaselist(EList<Phaselist> value);
	boolean validateName(String value);
	boolean validatePassword(String value);
}
