/**
 *
 * $Id$
 */
package Trialple.validation;

import Trialple.OptList;
import Trialple.Phaselist;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Trialple.SubModule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SubModuleValidator {
	boolean validate();

	boolean validateOptions(EList<OptList> value);
	boolean validatePhaselist(EList<Phaselist> value);
	boolean validateExecparallel(boolean value);
	boolean validatePassword(String value);
}
