/**
 *
 * $Id$
 */
package Trialple.validation;

import Trialple.Unit;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link Trialple.UnitDefinition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UnitDefinitionValidator {
	boolean validate();

	boolean validateUnit(EList<Unit> value);
	boolean validateName(String value);
	boolean validateSrcid(String value);
}
