/**
 *
 * $Id$
 */
package Trialple.validation;

import Trialple.ModuleType;
import Trialple.UnitModList;

/**
 * A sample validator interface for {@link Trialple.Unit}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UnitValidator {
	boolean validate();

	boolean validateTitle(String value);
	boolean validateUnitmodules(UnitModList value);
	boolean validateId(String value);
	boolean validateName(String value);
	boolean validateType(ModuleType value);
}
